import { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  id: {
    appName: "Money App",
    totalExpense: "Total Pengeluaran",
    expense: "Pengeluaran",
    income: "Pemasukan",
    thisMonth: "Bulan Ini",
    today: "Hari Ini",
    headButtonNotfication: "Aktifkan Notifikasi",
    descButtonNotfication: "Agar tau info apapun dari Money App",
    buttonNotfication: "Aktifkan",
    netBalance: "Sisa Uang",
    deficit: "Defisit",
    status_safe: "Keuangan aman terkendali 👍",
    status_danger: "Pengeluaran lebih besar dari pemasukan ⚠️",
    search_placeholder: "Cari transaksi...",
    period_date: "Pilih Periode",
    noEditTransfer: "Transaksi transfer tidak bisa diedit. Silakan hapus dan buat ulang",
    
    myWallet: "Dompet Saya",
    balance: "Saldo",
    addWallet: "Tambah",
    mutation: "Mutasi",
    manageWallet: "Kelola Dompet",
    deleteWalletTitle: "Hapus Dompet?",
    deleteWalletMsg: "Saldo dan semua riwayat transaksi di dompet ini akan hilang permanen.",
    walletAdded: "Dompet berhasil dibuat",
    walletUpdated: "Dompet berhasil diupdate",
    walletDeleted: "Dompet berhasil dihapus",
    ph_walletName: "Nama Dompet (cth: BCA)",
    ph_initialBalance: "Saldo Awal",
    cat_adjustment: "Koreksi Saldo",
    no_wallet_yet: "Belum ada dompet",
    btn_add_wallet: "Tambah",
    editBalanceNote: "Hanya ubah jika saldo tidak sesuai.",
    adjustBalanceTitle: "Penyesuaian Saldo?",
    adjustBalanceMsg: "Saldo berubah dari Rp {old} menjadi Rp {new}. Selisih {diff} akan dicatat otomatis sebagai 'Balance Adjustment'. Lanjutkan?",
    btn_yes_adjust: "Ya, Sesuaikan",
    
    history: "Riwayat Transaksi",
    noTransaction: "Tidak ada transaksi di bulan",
    addTransaction: "Tambah Transaksi",
    editTransaction: "Edit Transaksi",
    saveTransaction: "SIMPAN TRANSAKSI",
    updateTransaction: "UPDATE TRANSAKSI",
    saving: "Menyimpan...",
    currentBalance: "Saldo Saat Ini",
    
    amount: "NOMINAL",
    sourceWallet: "Sumber Dompet / Akun",
    chooseWallet: "Pilih Dompet",
    chooseCategory: "Pilih Kategori",
    no_category_yet: "Belum ada kategory",
    category: "Kategori",
    date: "Tanggal",
    note: "Catatan",
    noteOptional: "Catatan",
    manage: "Atur",
    
    ph_sourceFund: "Sumber Dana",
    ph_destWallet: "Masuk ke Dompet",
    ph_selectSource: "Pilih Sumber Dana",
    ph_selectDest: "Pilih Dompet Tujuan",
    ph_catExpense: "Kategori Pengeluaran",
    ph_catIncome: "Sumber Pemasukan",
    ph_selectCat: "Pilih Kategori",
    ph_selectSourceInc: "Pilih Sumber",
    ph_noteExp: "Contoh: Beli Nasi, Bensin...",
    ph_noteInc: "Contoh: Gaji, Bonus, THR...",

    menu_trans: "Transaksi",
    menu_stats: "Stats",
    menu_more: "Lainnya",
    
    more_title: "Menu Lainnya",
    profile: "Profil Akun",
    profile_desc: "Kelola informasi akun Anda",
    rekening: "Kelola Rekening",
    rekening_desc: "Tambah atau edit akun bank",
    pdf: "Laporan PDF",
    pdf_desc: "Download laporan keuangan",
    settings: "Pengaturan",
    settings_desc: "Tema",
    language: "Bahasa / Language",
    language_desc: "Ganti bahasa aplikasi",
    logout: "Keluar",
    logout_desc: "Sign out dari aplikasi",
    
    stats_total: "Total",
    analysisTitle: "Analisis Keuangan",
    view_category: "Kategori",
    view_trend: "Tren & Grafik",
    insightTitle: "💡 Wawasan",
    insightDesc: "Gunakan grafik tren untuk melihat pola pengeluaran tahunan Anda.",
    cashflowYear: "Arus Kas Tahun Ini",
    netIncomeTrend: "Tren Sisa Uang (Net Income)",
    remaining: "Sisa",
    dataMonth: "Data Bulan",
    dataYear: "Data Tahunan",
    btn_total_balance: "Klik untuk atur dompet",
    expenseTrend: "Tren Pengeluaran",

    manage_wallet_title: "Kelola Dompet",
    add_new_wallet: "Tambah Dompet Baru",
    edit_wallet: "Edit Dompet",
    label_wallet_name: "Nama Dompet",
    ph_wallet_name: "Contoh: BCA, OVO, Tunai...",
    label_wallet_type: "Tipe (Bank, E-Wallet, Tunai)",
    label_initial_balance: "Saldo Awal",
    btn_save: "Simpan",
    btn_update: "Update",
    btn_cancel: "Batal",
    confirm_del_wallet: "Hapus dompet ini? Saldo dan transaksi terkait akan hilang.",
    
    manage_cat_title: "Kelola Kategori",
    ph_add_cat: "Tambah kategori baru...",
    ph_edit_cat: "Edit nama kategori...",
    no_cat_yet: "Belum ada kategori",
    confirm_del_cat: "Hapus kategori ini? Transaksi terkait mungkin kehilangan label.",

    dark_mode: "Mode Gelap",
    active: "Aktif",
    inactive: "Nonaktif",
    notifications: "Notifikasi",
    notif_note: "*Notifikasi saat ini hanya simulasi UI.",
    
    export_menu: "Export Laporan",
    export_desc: "Unduh laporan (PDF/Excel)",
    format_file: "Format File",
    pdf_doc: "Dokumen PDF",
    excel_file: "File Excel",
    monthly: "Bulanan",
    yearly: "Tahunan",
    select_month: "Pilih Bulan",
    select_year: "Pilih Tahun",
    download: "Unduh",
    generating: "Memproses...",
    success_export: "Berhasil export",
    failed_export: "Gagal export",
    no_data: "Tidak ada data pada periode ini",
    processing: "Sedang Memproses...",
    download_btn: "Download PDF",
    success_download: "Berhasil didownload!",
    error_download: "Gagal download.",

    jan: "Januari", feb: "Februari", mar: "Maret", apr: "April", may: "Mei", jun: "Juni", 
    jul: "Juli", aug: "Agustus", sep: "September", oct: "Oktober", nov: "November", dec: "Desember",

    role_admin: "Admin",
    role_member: "Member",
    add_user: "Tambah User",
    switch_account: "Ganti Akun",
    switch_account_msg: "Anda akan keluar dari akun ini. Lanjutkan?",
    yes_switch: "Ya, Ganti",
    admin_mode_active: "Mode Administrator Aktif",
    manage_users: "Kelola User",

    confirm_title: "Konfirmasi",
    confirm_msg_default: "Apakah Anda yakin ingin melakukan tindakan ini?",
    cancel: "Batal",
    yes_delete: "Ya, Hapus",
    yes_confirm: "Ya, Lanjutkan",
    deleteCategoryTitle: "Hapus Kategori?",
    deleteCategoryMsg: "Transaksi dengan kategori ini akan kehilangan labelnya. Lanjutkan?",
    delete: "Hapus",
    manageCategory: "Kelola Kategori", 
    addCategoryPlaceholder: "Nama kategori baru...",
    
    logout_confirmation_msg: "Apakah Anda yakin ingin keluar dari aplikasi?",
    yes_logout: "Ya, Keluar",

    totalAssets: "Total Saldo (Aset)",
    noDescription: "Tanpa Keterangan", 

    deleteUserTitle: "Hapus User",
    deleteUserMsg: "Hapus user ini secara permanen? Akun ini akan bisa mendaftar ulang kembali nanti.",

    manage_users_title: "Kelola User",
    tab_users: "Daftar User",
    tab_logs: "Riwayat Login",
    status_active: "AKTIF",
    status_blocked: "DIBLOKIR",
    status_pending: "PENDING",
    status_online: "Online",
    status_offline: "Offline",
    btn_unblock: "Buka Blokir",
    btn_block: "Blokir",
    btn_approve: "Terima",
    btn_delete: "Hapus",
    empty_logs: "Belum ada data riwayat login.",
    email_unavailable: "Email tidak tersedia",
    confirm_delete_user_title: "Hapus User",
    confirm_delete_user_msg: "Hapus user ini secara permanen?",

    btn_broadcast: "Broadcast Notifikasi",
    btn_message: "Kirim Pesan",
    label_user: "Pengguna",
    user_activated: "User Diaktifkan",
    user_blocked: "User Diblokir",
    user_deleted: "User Dihapus",
    notif_send_to: "Kirim ke",
    notif_broadcast_title: "Broadcast ke Semua User",
    notif_label_title: "JUDUL",
    notif_placeholder_title: "Contoh: Info Pemeliharaan",
    notif_label_message: "PESAN",
    notif_placeholder_message: "Tulis pesan Anda di sini...",
    send: "Kirim",
    sending: "Mengirim...",
    notif_error_empty: "Judul dan pesan wajib diisi",
    notif_sent_to: "Terkirim ke",
    notif_broadcast_success: "Broadcast berhasil dikirim!",
    notif_error_failed: "Gagal mengirim notifikasi",
    
    modal_schedule_title: "Atur Notifikasi Otomatis",
    label_freq: "Frekuensi",
    label_exec_time: "Jam Kirim",
    label_day_week: "Pilih Hari",
    label_day_month: "Pilih Tanggal",
    ph_schedule_title: "Contoh: Jangan lupa catat!",
    ph_schedule_body: "Contoh: Catat pengeluaranmu hari ini agar...",
    freq_daily: "Setiap Hari",
    freq_weekly: "Mingguan (Hari Tertentu)",
    freq_monthly: "Bulanan (Tanggal Tertentu)",
    days_list: ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"],
    date_prefix: "Tanggal",
    btn_save_schedule: "Simpan Jadwal",
    success_save_schedule: "Jadwal notifikasi berhasil disimpan!",
    error_save_schedule: "Gagal menyimpan jadwal.",
    modal_schedule_list: "Daftar Jadwal Notifikasi",
    btn_add_schedule: "Buat Jadwal Baru",
    btn_back_list: "Kembali ke List",
    empty_schedule: "Belum ada jadwal otomatis yang dibuat.",
    confirm_del_schedule: "Hapus jadwal ini?",
    btn_edit_schedule: "Edit Jadwal",
    btn_update_schedule: "Update Jadwal",
    confirm_del_schedule_title: "Hapus Jadwal?",
    confirm_del_schedule_msg: "Jadwal notifikasi ini akan dihapus permanen dan tidak akan berjalan lagi.",

    debt_menu: "Catatan Hutang",
    debt_desc: "Kelola hutang & piutang",
    debt_title: "Buku Hutang",
    my_debt: "Hutang Saya",
    their_debt: "Piutang",
    add_debt: "Catat Baru",
    debt_person: "Nama Orang",
    debt_amount: "Jumlah",
    debt_date: "Jatuh Tempo",
    debt_type: "Tipe Catatan",
    mark_paid: "Tandai Lunas",
    debt_paid_confirm: "Hutang ini sudah lunas?",
    total_debt: "Total Hutang",
    total_receivable: "Total Piutang",
    no_debt_data: "Belum ada catatan hutang/piutang.",
    ph_person_name: "Contoh: Budi, Warung...",
    deleteDebtTitle: "Hapus Catatan?",
    deleteDebtMsg: "Catatan ini akan dihapus permanen.",
    payDebtTitle: "Lunasi Hutang?",
    payDebtMsg: "Apakah status hutang ini benar-benar sudah lunas?",
    status_paid: "Lunas",
    status_unpaid: "Belum Lunas",
    debt_note: "Catatan",
    ph_debt_note: "Contoh: Bekas makan siang, pulsa...",
    edit_debt: "Edit Catatan",
    debt_saved: "Catatan hutang berhasil disimpan",
    debt_updated: "Catatan berhasil diperbarui",
    debt_deleted: "Catatan berhasil dihapus",
    debt_settled: "Hutang ditandai lunas! 🎉",
    err_debt_name: "Nama orang harus diisi",
    err_debt_amount: "Jumlah harus lebih dari 0",
    time_label: "Waktu",
    optional: "Opsional",
    reminder_label: "Pengingat",
    remind_0_days: "Hari H (Pas Jatuh Tempo)",
    remind_1_day: "H-1 (Sehari Sebelumnya)",
    remind_3_days: "H-3 (3 Hari Sebelumnya)",
    remind_7_days: "H-7 (Seminggu Sebelumnya)",

    desc_adjustment_prefix: "Koreksi Saldo",

    selectCategoryAlert: "Pilih kategori dulu",
    selectWalletAlert: "Pilih dompet dulu",
    trxDeleted: "Transaksi berhasil dihapus",
    trxFailed: "Gagal hapus transaksi",
    btnClose: "Tutup",
    alertDeleteTransfer: "⚠️ INFO: Menghapus transfer ini akan OTOMATIS menghapus pasangannya di dompet lain. Saldo kedua dompet akan dikembalikan.",
    alertDeleteAdjustment: "⚠️ INFO: Menghapus penyesuaian ini akan MEMBATALKAN koreksi. Saldo dompet akan dikembalikan ke nilai sebelum disesuaikan.",
    alertDeleteDefault: "Hapus transaksi ini? Data tidak dapat dikembalikan.",

    transferTitle: "Transfer Dana",
    fromWallet: "DARI DOMPET",
    toWallet: "KE DOMPET",
    description: "CATATAN",
    ph_desc_transfer: "Contoh: Bayar hutang",
    fillAllFields: "Mohon lengkapi semua data",
    sameWalletError: "Dompet asal dan tujuan tidak boleh sama",
    transferSuccess: "Transfer Berhasil!",
    transferNow: "Transfer Sekarang",
    select: "Pilih",

    error_single_photo: "Hanya boleh upload 1 foto bukti transaksi!",
    error_photo_size: "Ukuran foto maksimal 5MB",
    trxSaved: "Transaksi berhasil disimpan!",
    trxUpdated: "Transaksi berhasil diupdate!",
  },

  en: {
    appName: "Money App",
    totalExpense: "Total Expense",
    expense: "Expense",
    income: "Income",
    thisMonth: "This Month",
    today: "Today",
    headButtonNotfication: "Enable Notifications",
    descButtonNotfication: "To know any information from Money App",
    buttonNotfication: "Activate",
    netBalance: "Net Balance",
    deficit: "Deficit",
    status_safe: "Finances are looking good 👍",
    status_danger: "Expenses exceed income ⚠️",
    search_placeholder: "Search transactions...",
    period_date: "Select Period",
    noEditTransfer: "Transfer transaction cannot be edited. Please delete and recreate it.",
    
    myWallet: "My Wallet",
    balance: "Balance",
    addWallet: "Add",
    mutation: "Flow",
    manageWallet: "Manage Wallets",
    deleteWalletTitle: "Delete Wallet?",
    deleteWalletMsg: "Balance and all transaction history in this wallet will be permanently lost.",
    walletAdded: "Wallet created successfully",
    walletUpdated: "Wallet updated successfully",
    walletDeleted: "Wallet deleted successfully",
    ph_walletName: "Wallet Name (e.g. Bank)",
    ph_initialBalance: "Initial Balance",
    cat_adjustment: "Balance Adjustment",
    no_wallet_yet: "No wallets yet",
    btn_add_wallet: "Add",
    editBalance: "Edit Balance (MANUAL)",
    editBalanceNote: "Only change if the balance does not match.",
    error_wallet_has_trx_dynamic: (count) => `Failed to delete! This wallet still has ${count} transaction history. Please delete transactions first.`,
    adjustBalanceTitle: "Adjust Balance?",
    adjustBalanceMsg: "Balance changed from Rp {old} to Rp {new}. The difference of {diff} will be recorded automatically as 'Balance Adjustment'. Continue?",
    btn_yes_adjust: "Yes, Adjust",
    
    history: "Transaction History",
    noTransaction: "No transactions in",
    addTransaction: "Add Transaction",
    editTransaction: "Edit Transaction",
    saveTransaction: "SAVE TRANSACTION",
    updateTransaction: "UPDATE TRANSACTION",
    saving: "Saving...",
    currentBalance: "Current Balance",
    
    amount: "AMOUNT",
    sourceWallet: "Source Wallet / Account",
    chooseWallet: "Select Wallet",
    chooseCategory: "Select Category",
    no_category_yet: "No category yet",
    category: "Category",
    date: "Date",
    note: "Note",
    noteOptional: "Note",
    manage: "Manage",
    
    ph_sourceFund: "Fund Source",
    ph_destWallet: "Target Wallet",
    ph_selectSource: "Select Fund Source",
    ph_selectDest: "Select Target Wallet",
    ph_catExpense: "Expense Category",
    ph_catIncome: "Income Source",
    ph_selectCat: "Select Category",
    ph_selectSourceInc: "Select Source",
    ph_noteExp: "Ex: Lunch, Gas, Coffee...",
    ph_noteInc: "Ex: Salary, Bonus, Gift...",

    menu_trans: "Trans",
    menu_stats: "Stats",
    menu_more: "More",
    
    more_title: "More Menu",
    profile: "Account Profile",
    profile_desc: "Manage your account info",
    rekening: "Manage Accounts",
    rekening_desc: "Add or edit bank accounts",
    pdf: "PDF Report",
    pdf_desc: "Download monthly report",
    settings: "Settings",
    settings_desc: "Theme",
    language: "Language / Bahasa",
    language_desc: "Change app language",
    logout: "Log Out",
    logout_desc: "Sign out from app",
    
    stats_empty: "No data available",
    stats_total: "Total",
    analysisTitle: "Financial Analysis",
    view_category: "Category",
    view_trend: "Trend & Graphs",
    insightTitle: "💡 Insight",
    insightDesc: "Use trend charts to see your annual spending patterns.",
    cashflowYear: "Cashflow This Year",
    netIncomeTrend: "Net Income Trend",
    remaining: "Remaining",
    noData: "No data available",
    dataMonth: "Month Data",  
    dataYear: "Annual Data",
    btn_total_balance: "Click to manage wallet",
    expenseTrend: "Expense Trend",

    manage_wallet_title: "Manage Wallets",
    add_new_wallet: "Add New Wallet",
    edit_wallet: "Edit Wallet",
    label_wallet_name: "Wallet Name",
    ph_wallet_name: "Ex: Chase Bank, Cash...",
    label_wallet_type: "Type (Bank, E-Wallet, Cash)",
    label_initial_balance: "Initial Balance",
    btn_save: "Save",
    btn_update: "Update",
    btn_cancel: "Cancel",
    confirm_del_wallet: "Delete this wallet? Balance and related transactions will be lost.",
    
    manage_cat_title: "Manage Categories",
    ph_add_cat: "Add new category...",
    ph_edit_cat: "Edit category name...",
    no_cat_yet: "No categories yet",
    confirm_del_cat: "Delete this category? Related transactions might lose their label.",

    dark_mode: "Dark Mode",
    active: "Active",
    inactive: "Inactive",
    notifications: "Notifications",
    notif_note: "*Notifications are currently UI simulation only.",

    export_menu: "Export Report",
    export_desc: "Download report (PDF/Excel)",
    format_file: "File Format",
    pdf_doc: "PDF Document",
    excel_file: "Excel File",
    monthly: "Monthly",
    yearly: "Yearly",
    select_month: "Select Month",
    select_year: "Select Year",
    download: "Download",
    generating: "Generating...",
    success_export: "Export successful",
    failed_export: "Export failed",
    no_data: "No data found for this period",
    processing: "Processing...",
    download_btn: "Download PDF",
    success_download: "Downloaded successfully!",
    error_download: "Download failed.",

    jan: "January", feb: "February", mar: "March", apr: "April", may: "May", jun: "June", 
    jul: "July", aug: "August", sep: "September", oct: "October", nov: "November", dec: "December",

    role_admin: "Administrator",
    role_member: "Member",
    add_user: "Add User",
    switch_account: "Switch Account",
    switch_account_msg: "You will be logged out. Continue?",
    yes_switch: "Yes, Switch",
    admin_mode_active: "Administrator Mode Active",
    manage_users: "Manage Users",

    confirm_title: "Confirmation",
    confirm_msg_default: "Are you sure you want to proceed?",
    cancel: "Cancel",
    yes_delete: "Yes, Delete",
    yes_confirm: "Yes, Continue",
    deleteCategoryTitle: "Delete Category?",
    deleteCategoryMsg: "Transactions with this category will lose their label. Continue?",
    delete: "Delete",
    manageCategory: "Manage Categories",
    addCategoryPlaceholder: "New category name...",
    
    logout_confirmation_msg: "Are you sure you want to log out from the application?",
    yes_logout: "Yes, Log Out",

    totalAssets: "Total Assets",
    noDescription: "No Description",

    deleteUserTitle: "Delete User",
    deleteUserMsg: "Permanently delete this user? This account will be able to register again later.",

    manage_users_title: "Manage Users",
    tab_users: "User List",
    tab_logs: "Login History",
    status_active: "ACTIVE",
    status_blocked: "BLOCKED",
    status_pending: "PENDING",
    status_online: "Online",
    status_offline: "Offline",
    btn_unblock: "Unblock",
    btn_block: "Block",
    btn_approve: "Approve",
    btn_delete: "Delete",
    empty_logs: "No login history found.",
    email_unavailable: "Email unavailable",
    confirm_delete_user_title: "Delete User",
    confirm_delete_user_msg: "Permanently delete this user?",

    btn_broadcast: "Broadcast Notification",
    btn_message: "Send Message",
    label_user: "User",
    user_activated: "User Activated",
    user_blocked: "User Blocked",
    user_deleted: "User Deleted",
    notif_send_to: "Send to",
    notif_broadcast_title: "Broadcast to All Users",
    notif_label_title: "TITLE",
    notif_placeholder_title: "Example: Maintenance Info",
    notif_label_message: "MESSAGE",
    notif_placeholder_message: "Write your message here...",
    send: "Send",
    sending: "Sending...",
    notif_error_empty: "Title and message are required",
    notif_sent_to: "Sent to",
    notif_broadcast_success: "Broadcast sent successfully!",
    notif_error_failed: "Failed to send notification",

    modal_schedule_title: "Set Auto Notification",
    label_freq: "Frequency",
    label_exec_time: "Execution Time",
    label_day_week: "Select Day",
    label_day_month: "Select Date",
    ph_schedule_title: "Ex: Don't forget to record!",
    ph_schedule_body: "Ex: Record your expenses today to...",
    freq_daily: "Daily",
    freq_weekly: "Weekly (Specific Day)",
    freq_monthly: "Monthly (Specific Date)",
    days_list: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    date_prefix: "Date",
    btn_save_schedule: "Save Schedule",
    success_save_schedule: "Notification schedule saved successfully!",
    error_save_schedule: "Failed to save schedule.",
    modal_schedule_list: "Scheduled Notifications List",
    btn_add_schedule: "Create New Schedule",
    btn_back_list: "Back to List",
    empty_schedule: "No automated schedules created yet.",
    confirm_del_schedule: "Delete this schedule?",
    btn_edit_schedule: "Edit Schedule",
    btn_update_schedule: "Update Schedule",
    confirm_del_schedule_title: "Delete Schedule?",
    confirm_del_schedule_msg: "This notification schedule will be permanently deleted.",

    debt_menu: "Debt Manager",
    debt_desc: "Manage debts & loans",
    debt_title: "Debt Book",
    my_debt: "I Owe",
    their_debt: "Owes Me",
    add_debt: "Add Record",
    debt_person: "Person Name",
    debt_amount: "Amount",
    debt_date: "Due Date",
    debt_type: "Record Type",
    mark_paid: "Mark as Paid",
    debt_paid_confirm: "Is this fully paid?",
    total_debt: "Total Payable",
    total_receivable: "Total Receivable",
    no_debt_data: "No debt records found.",
    ph_person_name: "Ex: John, Store...",
    deleteDebtTitle: "Delete Record?",
    deleteDebtMsg: "This record will be permanently deleted.",
    payDebtTitle: "Mark as Paid?",
    payDebtMsg: "Is this debt fully paid?",
    status_paid: "Paid",
    status_unpaid: "Unpaid",
    debt_note: "Note",
    ph_debt_note: "Ex: Lunch money, phone bill...",
    edit_debt: "Edit Record",
    debt_saved: "Debt record saved successfully",
    debt_updated: "Record updated successfully",
    debt_deleted: "Record deleted successfully",
    debt_settled: "Marked as paid! 🎉",
    err_debt_name: "Person name is required",
    err_debt_amount: "Amount must be greater than 0",
    time_label: "Time",
    optional: "Optional",
    reminder_label: "Reminder",
    remind_0_days: "On Due Date",
    remind_1_day: "1 Day Before",
    remind_3_days: "3 Days Before",
    remind_7_days: "1 Week Before",

    desc_adjustment_prefix: "Balance Adjustment",

    selectCategoryAlert: "Select a category first",
    selectWalletAlert: "Choose a wallet first",
    trxDeleted: "Transaction deleted successfully",
    trxFailed: "Failed to delete transaction",
    btnClose: "Close",
    alertDeleteTransfer: "⚠️ INFO: Deleting this transfer will AUTOMATICALLY delete its pair in the other wallet. Both wallet balances will be restored.",
    alertDeleteAdjustment: "⚠️ INFO: Deleting this adjustment will REVERSE the correction. Wallet balance will be restored.",
    alertDeleteDefault: "Delete this transaction? This action cannot be undone.",

    transferTitle: "Transfer Funds",
    fromWallet: "FROM WALLET",
    toWallet: "TO WALLET",
    description: "NOTE",
    ph_desc_transfer: "Ex: Debt payment",
    fillAllFields: "Please fill all fields",
    sameWalletError: "Source and destination wallets cannot be the same",
    transferSuccess: "Transfer Successful!",
    transferNow: "Transfer Now",
    select: "Select",

    error_single_photo: "You can only upload 1 proof photo!",
    error_photo_size: "Max photo size is 5MB",
    trxSaved: "Transaction saved successfully!",
    trxUpdated: "Transaction updated successfully!",
  }
};


export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('lang') || 'id');

  useEffect(() => {
    localStorage.setItem('lang', language);
  }, [language]);

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'id' ? 'en' : 'id'));
  };

  const t = translations[language];

  const translateCategory = (categoryName) => {
    if (!categoryName) return "";
    const nameLower = categoryName.toLowerCase();
    if (nameLower === "balance adjustment" || nameLower === "koreksi saldo") {
        return t.cat_adjustment;
    }
    return categoryName;
  };

  const translateDescription = (desc) => {
    if (!desc) return "";
    
    if (desc.startsWith("Balance Adjustment") || desc.startsWith("Koreksi Saldo")) {
        return desc
            .replace("Balance Adjustment", t.desc_adjustment_prefix)
            .replace("Koreksi Saldo", t.desc_adjustment_prefix);
    }
    
    return desc;
  };

  const value = {
    language,
    setLanguage,
    changeLanguage,
    toggleLanguage,
    t,
    translateCategory,
    translateDescription
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

